# Generated by Django 3.2.18 on 2023-05-31 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Psyholog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('room', models.IntegerField(verbose_name='room')),
                ('mon', models.CharField(max_length=255)),
                ('tue', models.CharField(max_length=255)),
                ('wed', models.CharField(max_length=255)),
                ('thu', models.CharField(max_length=255)),
                ('fri', models.CharField(max_length=255)),
                ('sat', models.CharField(max_length=255)),
                ('sun', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtenant.psyholog')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('diagnosis', models.CharField(max_length=255, null=True, verbose_name='diagnosis')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtenant.psyholog')),
                ('medicalcard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wtenant.medicalcard')),
            ],
        ),
    ]
